#! /bin/sh

launch() {
  # Kill all processes and launch argument
  killall -q $1
  while pgrep -u $UID -x $1 >/dev/null; do sleep 1; done
  $@ &
}

# Multiple Monitors
if [ -x ~/.config/bspwm/detect_monitors ]; then
  ~/.config/bspwm/detect_monitors
fi

# Panel
if [ -x ~/.config/bspwm/launch_polybar ]; then
  ~/.config/bspwm/launch_polybar
fi

# Background
xwallpaper --zoom ~/pictures/current
launch picom

# Notifications
launch dunst

# Xorg settings (don't use launch helper)
xmodmap $XDG_CONFIG_HOME/xorg/Xmodmap
xrdb $XDG_CONFIG_HOME/xorg/Xresources
xsetroot -cursor_name left_ptr

# Keybinds (must be after xmodmap)
launch sxhkd -c ~/.config/bspwm/sxhkdrc &

bspc monitor -d 1 2 3 4 5
bspc monitor primary -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#3B4252"
bspc config active_border_color "#B48EAD"
bspc config focused_border_color "#5E81AC"

bspc config top_padding 20

# Rules, start by removing all
bspc rule -r "*"
bspc rule -a Pavucontrol state=floating
bspc rule -a "*:*:Print" state=floating

bspc rule -a firefox desktop=^2 follow=on
bspc rule -a discord desktop=^6 follow=on

# Coord Math to center window: (screen_size / 2) - (window_size / 2)
# Set for 1920x1080 display. If different res, recalculate coords!

bspc rule -a FileManager state=floating rectangle=1000x610+460+235
bspc rule -a Calculator state=floating rectangle=1000x610+460+235
