#! /bin/sh

launch() {
  # Kill all processes and launch argument
  killall -q $1
  while pgrep -u $UID -x $1 >/dev/null; do sleep 1; done
  $@ &
}

# Panel
launch polybar -c ~/.config/bspwm/polybar.conf bar &

# Background
launch nitrogen --restore
launch picom

# Notifications
launch dunst

# Xorg settings (don't use launch helper)
xmodmap $XDG_CONFIG_HOME/xorg/Xmodmap

# Keybinds (must be after xmodmap)
launch sxhkd -c ~/.config/bspwm/sxhkdrc &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#282c34"
bspc config active_border_color "#477b7e"
bspc config focused_border_color "#5c6370"

bspc config top_padding 20

# Rules, start by removing all
bspc rule -r "*"
bspc rule -a Zathura state=tiled
bspc rule -a Calculator state=floating
bspc rule -a FileManager state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Newsboat desktop=^9 follow=on

# Coord Math: (screen_size / 2) - (window_size / 2)
# Set for 1920x1080 display. If different res, recalculate coords!

bspc rule -a Wttr state=floating rectangle=1000x610+460+235
