#!/bin/sh

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

awk_script='OFS="/" {if ($3 == "primary") print $1,$3; else print $1}'
for m in $(xrandr | grep '\<connected' | awk 'OFS="/" {if ($3 == "primary") print $1,$3; else print $1}'); do
  echo $m
  polybar -c ~/.config/bspwm/polybar.ini $m &
done
