#!/bin/bash

choices=(shutdown logout sleep restart lock)
operation="$(printf '%s\n' "${choices[@]}" | rofi -theme parmort-dmenu -dmenu)"

case $operation in
  shutdown) shutdown -h now;;
  restart) reboot;;
  sleep)
    dm-tool lock
    systemctl suspend
    ;;
  lock)
    dm-tool lock;;
  logout)
    rm /tmp/bspwm_started
    bspc quit
    ;;
esac

