#!/bin/bash

choice="$(printf "shutdown\\nlogout\\nsleep\\nrestart" | rofi -theme parmort-dmenu -dmenu)"

case $choice in
  shutdown) shutdown -h now;;
  restart) reboot;;
  sleep) systemctl suspend;;
  logout)
    rm /tmp/bspwm_started
    bspc quit
    ;;
esac

