#!/usr/bin/bash

if [ "$1" = "-" ] && [ -a ~/.eclf ]; then
  $EDITOR $(<~/.eclf)
  exit 0
fi

find ~/dotfiles/* -type f | grep -v ".*\.png" | cut --delimiter=/ -f 5- | fzf > ~/.eclf
$EDITOR $(<~/.eclf)
