#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

launch() {
  killall -q $1
  while pgrep -u $UID -x $1 >/dev/null; do sleep 1; done
  $@ &
}

startup() {
  [ ! -e /tmp/herbstluft_started ] && launch $@
}

hc emit_hook reload

hc keyunbind --all

# Load keybindings
launch sxhkd -c ~/.config/herbstluftwm/sxhkdrc

# Restore background
startup nitrogen --restore

# Panel
startup polybar -c ~/.config/herbstluftwm/polybar.conf bar

# Tray applets
launch nm-applet
launch pamac-tray
launch xmodmap ~/.Xmodmap

# Initialize tags
tag_names=( {1..9} )
hc rename default "${tag_names[0]}" || true
for i in ${tag_names[@]}; do hc add "${tag_names[$i]}"; done

hc set_layout horizontal
hc set default_frame_layout 1

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color
hc set frame_border_normal_color
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 1
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 4
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule windowid='ranger' floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

hc pad 0 20

touch /tmp/herbstluft_started
