#!/usr/bin/sh

chosen="$(lsblk -rpo "name,type,mountpoint" | awk '$2=="part"&&$3!~/\/boot|\/home$|SWAP/&&length($3)>1{printf "%s (%s)\n",$3,$1}' | fzf | awk '{print $1}')"

if [ -z $chosen ]; then
  notify-send "Could not unmount"
  exit
fi

sudo -A umount $chosen

notify-send "Unmounted drive\nfrom $chosen"
